spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/practicemappingdb
    username: postgres
    password: Babonproduction
    driver-class-name: org.postgresql.Driver